apiVersion: v2
name: lobby
description: Minestom lobby server for PrimCraft
type: application
version: 2026.2.2.1
appVersion: "2026.2.2"
keywords:
  - minecraft
  - minestom
  - lobby
home: https://github.com/PrimCraft/lobby
sources:
  - https://github.com/PrimCraft/lobby
maintainers:
  - name: bakas
